#!/bin/sh

if [ "$DAYTRADER_HOME" == "" ]; then
  echo DAYTRADER_HOME not defined
  exit 1
fi

CLASSPATH=$DAYTRADER_HOME/daytrader.d
CLASSPATH=$CLASSPATH:$DAYTRADER_HOME/daytrader.d/daytrader.jar
CLASSPATH=$CLASSPATH:$DAYTRADER_HOME/daytrader.d/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:$DAYTRADER_HOME/daytrader.d/log4j-1.2.14.jar
CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -Xmx128m daytrader.DayTrader $@"
eval $CMD
