#!/bin/sh

if [ "$DTRADER_HOME" == "" ]; then
  echo DTRADER_HOME not defined
  exit 1
fi

CLASSPATH=$DTRADER_HOME/dtrader.d
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/dtrader.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/log4j-1.2.14.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/commons-cli-1.4.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/commons-lang3-3.10.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/postgresql-9.3-1104.jdbc41.jar
CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -Xmx128m dtrader.DTrader $@"
eval $CMD
