#!/bin/sh

if [ "$DTRADER_HOME" == "" ]; then
  echo DTRADER_HOME not defined
  exit 1
fi

CLASSPATH=$DTRADER_HOME/dtrader.d
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/dtrader.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:$DTRADER_HOME/dtrader.d/log4j-1.2.14.jar
CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -Xmx128m dtrader.DTrader $@"
eval $CMD
