#!/bin/sh

DATABASE=dtrader
USER=dtrader
psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS SERIES CASCADE;
CREATE TABLE SERIES(
  ID SERIAL,
  OWNERID INTEGER REFERENCES USERS(ID) NOT NULL,
  NAME TEXT NOT NULL,
  PUB INTEGER NOT NULL CHECK(PUB = 0 OR PUB = 1), 
  HIDE INTEGER NOT NULL CHECK(HIDE = 0 OR HIDE = 1),
  UNIQUE (OWNERID, NAME),
  PRIMARY KEY(ID));

EOF
