#!/bin/sh

DATABASE=dtrader
USER=dtrader
psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS SERIES_DATA;
DROP TABLE IF EXISTS SERIES;

CREATE TABLE SERIES(
  ID VARCHAR(50) PRIMARY KEY, -- e.g. 'CORPCCC'
  TITLE VARCHAR(200), -- e.g. 'ICE BofA CCC & Lower US High Yield Index Effective Yield'
  SOURCE VARCHAR(50) NOT NULL, -- e.g. 'FRED'
  SOURCE_ID VARCHAR(50), -- e.g. 'BAMLH0A3HYCEY'
  NOTES TEXT, -- free-form notes 
  FREQ VARCHAR(10) NOT NULL); -- e.g. 'DAILY', '5MIN'

CREATE TABLE SERIES_DATA(
	SERIES_ID VARCHAR(50) REFERENCES SERIES(ID) NOT NULL,
	DATESTAMP DATE NOT NULL,
	IDX INTEGER); -- 0..78
EOF
