#!/bin/sh

DATABASE=dtrader
USER=dtrader
psql --username=$USER $DATABASE << EOF

DROP TABLE IF EXISTS SERIES CASCADE;
CREATE TABLE SERIES(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) UNIQUE NOT NULL, -- e.g. 'CORPCCC'
  SOURCE_NAME VARCHAR(50) NOT NULL, -- e.g. 'FRED'
  SOURCE_REF VARCHAR(50), -- e.g. 'BAMLH0A3HYCEY'
  NOTES VARCHAR(1000), -- free-form notes 
  FREQ CHAR(1) NOT NULL); -- e.g. 'D', '5'

CREATE TABLE SERIES_DATA(
	ID SERIAL PRIMARY KEY,
	SERIES_ID INTEGER REFERENCES SERIES(ID) NOT NULL,
	DATESTAMP DATE NOT NULL,
	IDX INTEGER); -- 0..78
EOF
